### PR TITLE
question upload

### PR DESCRIPTION
**Pull request by TanishqMehrunkarIIPSDAVV**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by nishant0708** [comment]
Check Difference Man Fix this
Screenshot 2024-10-01 153912

Screenshot 2024-10-01 153921

**Review by nishant0708 — CHANGES_REQUESTED** [review]
Check above

**Comment by nishant0708** [comment]
input field mai height difference hai

**Comment by nishant0708** [comment]
image
focus mai outline nhi aani chahiye

**Comment by Kartikey2011yadav** [comment]
created new pr with corrections pr #21

**Pull request closed without merging**
